#include "strings.h"
#include <string>
struct PARSE_STRINGS
{
    std::string string_name;//char* string_name;
    int   string_id;
}

PARSE_STRINGS[] = { 
    {"STRING_HELLO",STRING_HELLO},
    {"STRING_ENTER_NAME",STRING_ENTER_NAME},
    {"STRING_GENERATED_LOVER", STRING_GENERATED_LOVER},
    {"STRING_ENTER_LOVERS_NAME", STRING_ENTER_LOVERS_NAME},
    {"STRING_GENERATED_ENEMY", STRING_GENERATED_ENEMY},
    {"STRING_ENTER_OPPONENTS_NAME", STRING_ENTER_OPPONENTS_NAME},
    {"STRING_LEAVE_GENERATED_NAME", STRING_LEAVE_GENERATED_NAME},
    {"STRING_PLAYER_CHOSE", STRING_PLAYER_CHOSE},
    {"STRING_BROADCAST_CHOSE", STRING_BROADCAST_CHOSE},
    {"STRING_LOVER_TIRED_MESSAGE", STRING_LOVER_TIRED_MESSAGE},
    {"STRING_LOSE",STRING_LOSE},
    {"STRING_WON",STRING_WON},
    
                    

};
