#pragma once
enum
{
    LANG_EN_EN,
    LANG_RU_RU
};

enum
{
    STRING_HELLO,
    STRING_ENTER_NAME,
    STRING_GENERATED_LOVER,
    STRING_ENTER_LOVERS_NAME,
    STRING_GENERATED_ENEMY,
    STRING_ENTER_OPPONENTS_NAME,
    STRING_LEAVE_GENERATED_NAME,
    STRING_PLAYER_CHOSE,
    STRING_BROADCAST_CHOSE,
    STRING_LOVER_TIRED_MESSAGE,
    STRING_LOSE,
    STRING_WON
};